const skills = [
  {
    category: 'LLM & AI Systems',
    items: [
      'RAG',
      'GraphRAG',
      'Multi-Agent Orchestration',
      'LangGraph',
      'LangChain',
      'Few-shot Prompting',
      'LLM-as-judge',
      'Prompt Engineering',
      'ChromaDB',
      'FAISS',
      'OpenAI API',
      'Hugging Face',
      'BERT',
      'Sentence Transformers',
      'Tree-sitter',
    ],
  },
  {
    category: 'Machine Learning & Data Science',
    items: [
      'Scikit-learn',
      'PyTorch',
      'TensorFlow',
      'XGBoost',
      'SVM',
      'Random Forest',
      'Isolation Forest',
      'Feature Engineering',
      'Nested Cross-Validation',
      'Statistical Analysis',
      'Hypothesis Testing',
      'Model Evaluation',
      'SMOTE',
    ],
  },
  {
    category: 'Data Engineering & Cloud',
    items: [
      'PySpark',
      'Spark Structured Streaming',
      'Azure Databricks',
      'Azure Data Factory',
      'Azure Monitor',
      'Azure DevOps',
      'ETL Pipelines',
      'asyncio',
      'Data Modeling',
      'MongoDB',
    ],
  },
  {
    category: 'MLOps & Software',
    items: [
      'MLflow',
      'Docker',
      'Kubernetes',
      'GitHub Actions',
      'CI/CD',
      'Python',
      'SQL',
      'FastAPI',
      'Flask',
      'Streamlit',
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Git',
      'Testing',
    ],
  },
];

export default skills;