const skills = [
  {
    category: 'Machine Learning & Data Science',
    items: [
      'Scikit-learn',
      'XGBoost',
      'SVM',
      'Random Forest',
      'Logistic Regression',
      'Feature Engineering',
      'Experimentation',
      'Hypothesis Testing',
      'Statistical Analysis',
      'Model Evaluation',
      'Cross-Validation',
      'SMOTE',
    ],
  },
  {
    category: 'AI / NLP / LLMs',
    items: [
      'Hugging Face',
      'Transformers',
      'Prompt Engineering',
      'BERT',
      'Semantic Similarity',
      'Evaluation Pipelines',
      'Tree-sitter',
      'LLM Summarization',
      'Structured Output',
      'OpenAI API',
      'Sentence Transformers',
      'FAISS',
    ],
  },
  {
    category: 'Data Engineering & Cloud',
    items: [
      'Spark',
      'Databricks',
      'Azure',
      'Azure Data Factory',
      'ETL Pipelines',
      'Structured Streaming',
      'Data Modeling',
      'Data Validation',
      'Orchestration',
      'MongoDB',
    ],
  },
  {
    category: 'Software / MLOps / Product',
    items: [
      'Python',
      'SQL',
      'FastAPI',
      'Streamlit',
      'Flask',
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Git',
      'MLflow',
      'CI/CD',
      'Docker',
      'Kubernetes',
      'Testing',
    ],
  },
];

export default skills;